apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - svc.yaml

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value: 
          - name: XLOG_DOMAIN
            value: xlog.page
    target:
      kind: Deployment
      name: .*