apiVersion: v1
kind: Service
metadata:
  name: xlog-lb
  namespace: crossbell
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    networking.gke.io/internal-load-balancer-subnet: "dev-loadbalancer"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: xlog-caddy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
