apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xlog-caddy
  namespace: crossbell
spec:
  maxReplicas: 20
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xlog-caddy
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 150