apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - hpa.yaml
  - hpa-validator.yaml
  - svc
  - oia

patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env"
        value:
          - name: XLOG_DOMAIN
            value: xlog.app
          - name: OTEL_SERVICE_NAME
            value: xlog-caddy
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://jaeger-collector.guardian:4317
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: 'true'
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc
    target:
      kind: Deployment
      name: .*