apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlog-caddy
  namespace: crossbell
spec:
  selector:
    matchLabels:
      app: xlog-caddy
  template:
    metadata:
      labels:
        app: xlog-caddy
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: caddy
          image: flosspicks/xlog-caddy:latest
          imagePullPolicy: Always
          args:
          - run
          - --config
          - /app/Caddyfile
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: xlog-caddy
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 8080
              name: metrics
          livenessProbe:
            httpGet:
              port: metrics
              path: /
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: metrics
              path: /
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: caddyfile
              mountPath: /app
      volumes:
        - name: caddyfile
          configMap:
            name: xlog-caddy
