apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - ../validator

configMapGenerator:
  - name: xlog-caddy
    options:
      disableNameSuffixHash: true
    files:
      - Caddyfile
