apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - svc.yaml
  - deploy.yaml

configMapGenerator:
  - name: xlog-caddy-validator
    options:
      disableNameSuffixHash: true
    files:
      - app.py
