apiVersion: v1
kind: Service
metadata:
  name: xlog-caddy-validator
  namespace: crossbell
spec:
  type: ClusterIP
  selector:
    app: xlog-caddy-validator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
