name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: flosspicks/xlog-caddy
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/daedalus
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: crossbell
      releaseName: xlog-caddy
      revision: main
      dir: deploy/dev
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  deploy-prod:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/daedalus
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: crossbell
      releaseName: xlog-caddy
      revision: main
      dir: deploy/prod
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
